USE [master]
GO
CREATE LOGIN [Administrator] WITH PASSWORD=N'Administrator1', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF

CREATE LOGIN [Client] WITH PASSWORD=N'Client1', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF

CREATE LOGIN [Mechanic] WITH PASSWORD=N'Mechanic1', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF

CREATE LOGIN [StoreMan] WITH PASSWORD=N'StoreMan1', DEFAULT_DATABASE=[master], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO
USE [MiRas]
GO
CREATE USER [Administrator] FOR LOGIN [Administrator]
CREATE USER [Client] FOR LOGIN [Client]
CREATE USER [Mechanic] FOR LOGIN [Mechanic]
CREATE USER [StoreMan] FOR LOGIN [StoreMan]
GO
USE [MiRas]
GO
ALTER ROLE [Administrator_role] ADD MEMBER [Administrator]
ALTER ROLE [Client_role] ADD MEMBER [Client]
ALTER ROLE [Mechanic_role] ADD MEMBER [Mechanic]
ALTER ROLE [StoreMan_role] ADD MEMBER [StoreMan]
GO